name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CI: "false"
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."

      - name: ä¸‹è½½ç¼–è¯‘å·¥å…·
        run: |
          mkdir -p $GITHUB_WORKSPACE/kernel_workspace
          cd $GITHUB_WORKSPACE/kernel_workspace
          # mkdir clang-aosp
          # git clone https://github.com/tomxi1997/Toolchain.git clang-aosp --depth=1
          wget -q https://github.com/ZyCromerZ/Clang/releases/download/19.0.0git-20240125-release/Clang-19.0.0git-20240125.tar.gz
          mkdir -p clang
          tar -xzf Clang-19.0.0git-20240125.tar.gz -C clang
          # sudo apt-get update
          # sudo apt install -y curl python2 llvm lld wget vim git ccache automake flex lzop bison gperf build-essential zip zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler kmod python3 python3-pip
          $GITHUB_WORKSPACE/kernel_workspace/clang/bin/clang --version

      - name: å…‹éš†æºç ä¸è¡¥ä¸
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          git clone https://github.com/jhchong94/kernel_xiaomi_sm8250_n0kernel --depth=1 android_kernel
          git clone https://github.com/zzh20188/AUTO_BUILD.git src
          git clone https://gitlab.com/simonpunk/susfs4ksu.git --depth=1 susfs
      - name: å®‰è£…KSUN
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs

      - name: é›†æˆKSU
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel
          cp $GITHUB_WORKSPACE/kernel_workspace/src/patches/* .
          patch -p1 < new_defconfig.patch
          patch -p1 < non-kprobes.patch
          tail -n 10 arch/arm64/configs/vendor/umi_defconfig

      - name: åº”ç”¨susfsè¡¥ä¸
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel
          cp $GITHUB_WORKSPACE/kernel_workspace/susfs/kernel_patches/fs/* ./fs/
          cp $GITHUB_WORKSPACE/kernel_workspace/susfs/kernel_patches/include/linux/* ./include/linux/
          cp $GITHUB_WORKSPACE/kernel_workspace/susfs/kernel_patches/50_add_susfs_in_kernel-4.19.patch .
          patch -p1 < 50_add_susfs_in_kernel-4.19.patch
          patch -p1 < after_patch_fix.patch
        
      # - name: å¼€å§‹æ„å»º
      #   run: |
      #     export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang/bin:$PATH
      #     echo "Updated PATH: $PATH"
      #     clang --version
          
      #     cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel
      #     # ls $GITHUB_ACTION_PATH
      #     make -j$(nproc --all) CC=clang O=out ARCH=arm64 CLANG_TRIPLE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1 CROSS_COMPILE=aarch64-buildroot-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-androideabi- vendor/umi_defconfig
      #     make -j8 CC=clang O=out ARCH=arm64 CLANG_TRIPLE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1 CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi-    
      
      # - name: æŸ¥çœ‹æˆæœ
      #   run: |
      #       cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel
      #       ls out/arch/arm64/boot/Image
      #       strings out/arch/arm64/boot/Image | grep "Linux version"
          
