name: GitHub Actions Demo
run-name: ${{ github.actor }} æ­£åœ¨ç¼–è¯‘ éªé¾™865 å°ç±³ç³»åˆ—å†…æ ¸ï¼ğŸš€ ğŸš€
on:
  workflow_dispatch:
    inputs:
      phone:
        description: 'é€‰æ‹©æ‰‹æœºå‹å·ï¼š'
        required: true
        default: 'å°ç±³10'
        type: choice
        options:
          - å°ç±³10
          - å°ç±³10pro
      susfs:
        description: 'æ˜¯å¦é›†æˆSUSFS'
        required: true
        type: boolean
      version:
        description: 'è‡ªå®šä¹‰ç‰ˆæœ¬åï¼ˆå¦‚perf-xxxï¼‰/å¯ä¸ºç©ºï¼ˆåˆ™ä¸ºn0kernelï¼‰'
        required: false
        type: string
jobs:
  build_job:
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CI: "false"
    steps:

      - name: 1.ä¸‹è½½ç¼–è¯‘å·¥å…·
        run: |
          mkdir -p $GITHUB_WORKSPACE/kernel_workspace
          cd $GITHUB_WORKSPACE/kernel_workspace
          wget -q https://github.com/ZyCromerZ/Clang/releases/download/19.0.0git-20240125-release/Clang-19.0.0git-20240125.tar.gz
          mkdir -p clang
          tar -xzf Clang-19.0.0git-20240125.tar.gz -C clang

      - name: 2.å…‹éš†æºç ä¸è¡¥ä¸
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          git clone https://github.com/jhchong94/kernel_xiaomi_sm8250_n0kernel --depth=1 android_kernel
          # git clone https://github.com/zzh20188/AUTO_BUILD.git src
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b kernel-4.19 --depth=1 susfs

      - name: 3.å®‰è£…KSUN
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs

      - name: 4.0æ£€å‡ºä»“åº“è¡¥ä¸
        uses: actions/checkout@v4
      - name: 4.5é›†æˆKSU
        run: |
          ls
          echo "è¿›å…¥æºç ç›®å½•"
          cd ./kernel_workspace/android_kernel
          cp ./patches/* .
          patch -p1 < new_defconfig.patch
          patch -p1 < non-kprobes.patch
          tail -n 10 arch/arm64/configs/vendor/umi_defconfig

      - name: 5.åº”ç”¨susfsè¡¥ä¸
        run: |
          if [ ${{ inputs.susfs }} = true ]; then
            echo "é€‰æ‹©é›†æˆsusfs"
            cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel
            echo "å¤åˆ¶susfs/kernel_patches/fs/* çš„å†…å®¹"
            cp $GITHUB_WORKSPACE/kernel_workspace/susfs/kernel_patches/fs/* ./fs/
            echo "å¤åˆ¶susfs/kernel_patches/include/linux/* çš„å†…å®¹"
            cp $GITHUB_WORKSPACE/kernel_workspace/susfs/kernel_patches/include/linux/* ./include/linux/
            echo "å¤åˆ¶susfså†…æ ¸æºç è¡¥ä¸"
            cp $GITHUB_WORKSPACE/kernel_workspace/susfs/kernel_patches/50_add_susfs_in_kernel-4.19.patch .
            echo "æ‰§è¡Œsusfsè¡¥ä¸"
            patch -p1 < 50_add_susfs_in_kernel-4.19.patch || true
            echo "ä¿®å¤"
            patch -p1 < after_patch_fix.patch            
          else
            echo "è·³è¿‡é›†æˆsusfs"
          fi
        
      - name: 6.å¼€å§‹æ„å»º
        run: |
          echo "$GITHUB_WORKSPACE/kernel_workspace/clang/bin" >> "$GITHUB_PATH"
          # export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang/bin:$PATH
          echo "Updated PATH: $PATH"
          clang --version
          
          cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel
          # è‡ªå®šä¹‰ç‰ˆæœ¬
          if [ ! -z ${{ inputs.version }} ]; then
            echo "ä¸ä¸ºç©º"
            sed -i '$s|echo "\$res"|echo "\$res-${{ inputs.version }}"|' ./scripts/setlocalversion
          else
            echo "å­—ç¬¦ä¸²ä¸ºç©º"
          fi

          if [ ${{ inputs.phone }} = 'å°ç±³10' ]; then
            echo "é€‰æ‹©å°ç±³10é…ç½®"
            DEFCONFIG=vendor/umi_defconfig
          elif [ ${{ inputs.phone }} = 'å°ç±³10pro' ]; then
            echo "é€‰æ‹©å°ç±³10proé…ç½®"
            DEFCONFIG=vendor/cmi_defconfig
          else
            echo "éæ³•å†…å®¹"
          fi

          echo "å½“å‰é…ç½®ä¸º $DEFCONFIG"

          make -j$(nproc --all) CC=clang O=out ARCH=arm64 CLANG_TRIPLE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1 CROSS_COMPILE=aarch64-buildroot-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-androideabi- $DEFCONFIG
          make -j8 CC=clang O=out ARCH=arm64 CLANG_TRIPLE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1 CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi-    
      
      - name: 7.æŸ¥çœ‹æˆæœ
        run: |
            cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel/out/arch/arm64/boot
            ls
            strings Image | grep "Linux version"
            cp Image ./Anykernel/

      - name: 8.ä¸Šä¼ åˆ·å…¥åŒ…
        uses: actions/upload-artifact@v4
        with:
          name: KSUN_SUS_${{ inputs.phone }}.zip
          path: ./Anykernel/*
          retention-days: 2
